import type { Metadata } from "next";
import "./globals.css";
import HeaderPage from "./components/Header/Header";
import Tag from "./components/Tag/Tag";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderPage />
        <Tag />
        {children}
      </body>
    </html>
  );
}
